services:
  - type: web
    name: churn-prediction-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. uvicorn backend.app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
